# echo HOST_ADDR=$(curl -s https://eth0.me) >> .env && docker-compose up -d 
version: '3'
services:
  openvpn:
    container_name: openvpn
    image: vo1dbin/openvpn:latest
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "1194:1194/udp"
      - "80:8080/tcp"
    env_file: .env
    volumes:
      - ./openvpn_conf:/opt/openvpn_data/clients

